# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('nr_rooms', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('last_name', models.CharField(max_length=140)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=140)),
                ('hotel_id', models.IntegerField()),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('total_rooms', models.IntegerField()),
                ('total_cost', models.FloatField()),
            ],
        ),
    ]
